export const NODE_ENV = 'development'
export const SENTRY_DSN = ''
export const AUTH0_DOMAIN = ''
export const AUTH0_CLIENTID = ''
export const AUTH0_AUDIENCE = ''
export const API_HOST = ''
export const S3_URL_PATH = 'http://localhost:3000/webhook/signed_url'
